version: '2'

services:
  vault:
        image: vault:0.10.1
        ports:
          - "8200:8200"
        volumes:
          - ./resources/vault.hcl:/vault/config/vault.hcl
        environment:
          - VAULT_DEV_ROOT_TOKEN_ID=87e7784b-d598-44fe-8962-c7c345a11eed
          - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
          - SKIP_SETCAP=true
          - disable_mlock=true
